#!/bin/bash
set -e

if [ ! -f /workspace/config ]; then
  echo "Missing /workspace/config"
  exit -1
fi
. /workspace/config

COMMITTER_NAME=${COMMITTER_NAME:?"COMMITTER_NAME is not set"}
COMMITTER_EMAIL=${COMMITTER_EMAIL:?"COMITTER_EMAIL is not set"}
RELEASE_DATE=${RELEASE_DATE:-`date +%Y-%m-%d -d 'thursday'`}
RELEASE_BRANCH=${RELEASE_BRANCH:?"RELEASE_BRANCH is not set"}
RELEASE_VERSION=${RELEASE_VERSION:?"RELEASE_VERSION is not set"}
GPG_KEY=${GPG_KEY:?"GPG_KEY is not set"}
CONFIGURE_AC=${CONFIGURE_AC:-"configure.ac"}
MAKE_JOBS=${MAKE_JOBS:-`nproc`}
TEST_JOBS=${TEST_JOBS:-`nproc`}

PHP_REPO_FETCH=${PHP_REPO_FETCH:-"https://github.com/php/php-src"}
PHP_REPO_PUSH=${PHP_REPO_PUSH:-"git@github.com:php/php-src"}

# Translate version
VERSION_MAJOR=$(echo "$RELEASE_VERSION" | cut -d "." -f 1)
VERSION_MINOR=$(echo "$RELEASE_VERSION" | cut -d "." -f 2)
VERSION_PATCH=$(echo "$RELEASE_VERSION" | cut -d "." -f 3 | egrep -o "[0-9]+" | head -n 1)
POINT_RELEASE_BRANCH="PHP-${VERSION_MAJOR}.${VERSION_MINOR}"
RC_RELEASE_BRANCH="${POINT_RELEASE_BRANCH}.${VERSION_PATCH}"
if [ "$VERSION_PATCH" != "$(echo $1 | cut -d '.' -f 3)" ]; then
  # This is an alpha/beta/RC
  OFFSET=$((${#VERSION_PATCH}+1))
  VERSION_EXTRA=$(echo "$RELEASE_VERSION" | cut -d "." -f 3 | cut -c "$OFFSET"-)
fi
VERSION_ID=$(($((VERSION_MAJOR*10000))+$((VERSION_MINOR*100))+$((VERSION_PATCH+0))))

# Prepare GPG stuff
if [ ! -d /tmp/gnupg ]; then
  echo Please bind mount your .gnupg folder to  /tmp/gnupg
  exit 1
fi

mkdir -p /root/.gnupg
chmod 700 /root/.gnupg
cp -Rp /tmp/gnupg/* /root/.gnupg/

# Force TTY pinentry
echo > /root/.gnupg/gpg-agent.conf <<EOF
default-cache-ttl 1800
max-cache-ttl 7200
pinentry-program /usr/bin/pinentry-tty
EOF

# Reveal our plan
echo "php-release builder"
echo "-------------------"
echo "COMMITTER_NAME=${COMMITTER_NAME}"
echo "COMMITTER_EMAIL=${COMMITTER_EMAIL}"
echo "GPG_KEY=${GPG_KEY}"
echo "RELEASE_DATE=${RELEASE_DATE}"
echo -n "RELEASE_BRANCH="
if [  -z "$CUT_RELEASE_BRANCH" ]; then
  echo "$RELEASE_BRANCH"
else
  echo "$CUT_RELEASE_BRANCH (new branch cut from $RELEASE_BRANCH)"
fi
echo "RELEASE_VERSION=${RELEASE_VERSION}"
echo "-------------------"

# Clean up workspace
cd /workspace
rm -rf php-src
rm -f  log/{config,make,tests}.{debug-,}[nz]ts.log

# Clone from source (using public readable),
# Configure commiter,
# then update branch to push destination
echo "Cloning from ${PHP_REPO_FETCH}"
cd /workspace
git clone -b "$RELEASE_BRANCH" -o upstream --depth="${CLONE_DEPTH:-1000}" "${PHP_REPO_FETCH}"

cd /workspace/php-src

if [ ! -z "${CUT_RELEASE_BRANCH}" ]; then
  echo "Cutting ${CUT_RELEASE_BRANCH} from ${RELEASE_BRANCH}"
  git checkout -b "${CUT_RELEASE_BRANCH}"
fi

echo "Building $RELEASE_VERSION from ${CUT_RELEASE_BRANCH:-$RELEASE_BRANCH}"
if [[ "$VERSION_EXTRA" != alpha* ]]; then
  if [ "$POINT_RELEASE_BRANCH" != "$RELEASE_BRANCH" -a \
       "$RC_RELEASE_BRANCH" != "$RELEASE_BRANCH" -a \
       "$RC_RELEASE_BRANCH" != "$CUT_RELEASE_BRANCH" ]; then
    echo "******************************************" 1>&2
    echo -n "** WARNING: $RELEASE_VERSION probably belongs on " 1>&2
    echo -n "$POINT_RELEASE_BRANCH or $RC_RELEASE_BRANCH" 1>&2
    echo ", but is being cut from $RELEASE_BRANCH" 1>&2
    echo -ne '\007\007\007'
    echo "******************************************" 1>&2
    sleep 15
  fi
fi

# Get going
git config user.name "$COMMITTER_NAME"
git config user.email "$COMMITTER_EMAIL"
git config user.signingkey  "$GPG_KEY"
git config commit.gpgsign true
git config tag.gpgSign true
git config merge.log true
git remote set-url upstream --push "${PHP_REPO_PUSH}"

GPG_TTY=$(tty)
export GPG_TTY

# Update NEWS
cd /workspace/php-src
NEWS_FILE_SLUG="$(date -d ${RELEASE_DATE} '+%d %b %Y'), PHP ${RELEASE_VERSION}"
sed -i \
    -e "s/?? ??? \(????\|[0-9]\{4\}\),.*/${NEWS_FILE_SLUG}/g" \
    NEWS
if [ ! -z "$(git diff -- NEWS)" ]; then
  git add NEWS
  git commit -m "Update NEWS for PHP ${RELEASE_VERSION}"
  git show | cat -
elif [ -z "$(grep "${NEWS_FILE_SLUG}" NEWS)" ]; then
  echo "NEWS file has neither target release date, nor ?? ??? placeholder" 1>&2
  echo "Correct this and try again." 1>&2
  exit 1
fi

# Update CREDITS
cd /workspace/php-src
scripts/dev/credits
if [ ! -z "$(git diff ext/standard/credits_{ext,sapi}.h)" ]; then
  git add ext/standard/credits_{ext,sapi}.h
  git commit -m "Update CREDITS for PHP ${RELEASE_VERSION}"
  git show | cat -
fi

# Version bump will be on a spur ending at tag:php-${RELEASE_VERSION}
# NEWS bump will be on ${RELEASE_BRANCH}
SPURBASE_COMMIT=$(git rev-parse HEAD)

# Update main/php_version.h
cd /workspace/php-src
echo \
"/* automatically generated by configure */
/* edit $CONFIGURE_AC to change version number */
#define PHP_MAJOR_VERSION $VERSION_MAJOR
#define PHP_MINOR_VERSION $VERSION_MINOR
#define PHP_RELEASE_VERSION $VERSION_PATCH
#define PHP_EXTRA_VERSION \"$VERSION_EXTRA\"
#define PHP_VERSION \"$RELEASE_VERSION\"
#define PHP_VERSION_ID $VERSION_ID" > main/php_version.h
git add main/php_version.h

# Update Zend/zend.h
cd /workspace/php-src
if [ -z "$ZEND_VERSION" ]; then
    # Either configure ZEND_VERSION in config file, or compute it relative to PHP version
    if [ "$VERSION_MAJOR" -lt 7 ]; then
        ZEND_VERSION="$((VERSION_MAJOR - 3))"
    else
        ZEND_VERSION="$(($VERSION_MAJOR - 4))"
    fi
    ZEND_VERSION="${ZEND_VERSION}.${VERSION_MINOR}.${VERSION_PATCH}${VERSION_EXTRA}"
fi
sed -i -e "s/^#define ZEND_VERSION \".*\"$/#define ZEND_VERSION \"${ZEND_VERSION}\"/g" Zend/zend.h
git add Zend/zend.h

# Bump API numbers on RC1
if [ "$VERSION_PATCH" -eq 0 -a "$VERSION_EXTRA" = 'RC1' ]; then
  bump_api() {
    API_DATE=$(date +%y%m%d -d "$RELEASE_DATE")
    sed -i -E -e "s/(define ${2}\\s.*)[0-9]{6}/\\1${API_DATE}/" "$1"
    git add "$1"
  }

  bump_api "main/php.h" "PHP_API_VERSION"
  bump_api "Zend/zend_extensions.h" "ZEND_EXTENSION_API_NO"
  bump_api "Zend/zend_modules.h" "ZEND_MODULE_API_NO"
fi

# Update configure.ac
cd /workspace/php-src
# First four lines for 7.3 and earlier
# Last transformation for 7.4 and later
sed -i \
    -e "s/^AC_INIT(\[PHP\], *\[[^\]]*\?\],/AC_INIT([PHP],[$RELEASE_VERSION],/g" \
    -e "s/^AC_INIT(\[PHP\], *\[[^,]*\],/AC_INIT([PHP],[$RELEASE_VERSION],/g" \
    "$CONFIGURE_AC"
git add "$CONFIGURE_AC"

# commit
cd /workspace/php-src
git commit -m "Update versions for PHP ${RELEASE_VERSION}"
git show | cat -
TAG_COMMIT=$(git rev-parse HEAD)

########

make_test() {
  LOGEXT="nts"
  if [ "$2" -eq 1 ]; then
    LOGEXT="zts"
  fi
  if [ "$1" -eq 1 ]; then
    LOGEXT="debug-$LOGEXT"
  fi
  echo "----------------------"
  echo "Building PHP $LOGEXT"

  # Build PHP
  mkdir -p /workspace/log
  cd /workspace/php-src
  git clean -xfdq

  CONFIG_LOG_FILE=/workspace/log/config.$LOGEXT.log
  MAKE_LOG_FILE=/workspace/log/make.$LOGEXT.log
  TEST_LOG_FILE=/workspace/log/tests.$LOGEXT.log

  CONFIG_ARGS=""
  if [ "$1" -eq 1 ]; then
    CONFIG_ARGS="$CONFIG_ARGS --enable-debug"
  fi
  if [ "$2" -eq 1 ]; then
    CONFIG_ARGS="$CONFIG_ARGS --enable-zts"
  fi

  ./buildconf --force
  ./configure --disable-all $CONFIG_ARGS --enable-opcache-jit 2>&1 | tee $CONFIG_LOG_FILE
  make -j${MAKE_JOBS} 2>&1 | tee $MAKE_LOG_FILE

  BUILT_VERSION=$(./sapi/cli/php -n -v | head -n 1 | cut -d " " -f 2)
  if [ "$BUILT_VERSION" != "$RELEASE_VERSION" ]; then
    echo "**Panic: RELEASE_VERSION=${RELEASE_VERSION}, but BUILT_VERSION=${BUILT_VERSION}"
    exit 1
  fi

  make test TEST_PHP_ARGS="-q -j${TEST_JOBS} --show-diff" 2>&1 | tee $TEST_LOG_FILE

  if [ "$?" -ne 0 -a ${ABORT_ON_TEST_FAILURES:-"0"} -ne 0 ]; then
    exit $?
  fi
}

MAKE_TESTS="${MAKE_TESTS:-2}"
if [ "${MAKE_TESTS}" -ge 1 ]; then
  # 0 No tests
  # 1 Debug-ZTS only
  # 2 All tests
  if [ "${MAKE_TESTS}" -ge 2 ]; then
    make_test 0 0
    make_test 0 1
    make_test 1 0
  fi
  make_test 1 1
fi

# Make tarballs/stubs and relocate them
cd /workspace/php-src
echo "-----------------"
echo "Bundling tarballs"
git tag "php-$RELEASE_VERSION" "$TAG_COMMIT" -m "Tag for php-$RELEASE_VERSION"
scripts/dev/makedist "php-$RELEASE_VERSION"
scripts/dev/gen_verify_stub $RELEASE_VERSION $GPG_KEY > php-$RELEASE_VERSION.manifest

# Back off of release spur now that we've tagged
git reset "${SPURBASE_COMMIT}" --hard

# Update NEWS (if requested)
cd /workspace/php-src
if [ ! -z "$RELEASE_NEXT" ]; then
  sed -i \
      -e "3s/^/?? ??? ????, PHP ${RELEASE_NEXT}\n\n\n/" \
      NEWS
  git add NEWS
  git commit -m "Update NEWS for ${RELEASE_NEXT}"
fi

if [ ! -z "$COMMITTER_UID" -a ! -z "$COMMITTER_GID" ]; then
  chown -R "${COMMITTER_UID}:${COMMITTER_GID}" /workspace/php-src
fi

# Truncate COMMIT hash for readability
TAG_COMMIT=$(echo "${TAG_COMMIT}" | cut -c 1-10)

# Output finalization instructions
echo "-----------------"
echo "Tarballs prepared"

echo "Verify what you're about to push as a tagged release:"
echo "$ git log -p 'upstream/${RELEASE_BRANCH}..php-${RELEASE_VERSION}'"
echo ""
if [ ! -z "$RELEASE_NEXT" ]; then
  echo "And as the prepared NEWS entry for the next release:"
  echo "$ git log -p 'upstream/${RELEASE_BRANCH}..'"
  echo ""
fi

echo "If all is well, push it to ${PHP_REPO_PUSH}!"
echo "$ git push upstream 'php-$RELEASE_VERSION' '${CUT_RELEASE_BRANCH:-${RELEASE_BRANCH}}'"
echo ""

echo "Make the tarballs available for testing:"
if [ -z "$VERSION_EXTRA" ]; then
  echo "1. Copy workspace/php-src/php-$RELEASE_VERSION.tar.{gz,bz2,xz}{,.asc} to php-distributions repository"
else
  echo "1. Copy workspace/php-src/php-$RELEASE_VERSION.tar.{gz,bz2,xz}{,.asc} to \$USER@downloads.php.net:public_html/"
fi
echo "2. Contact release-managers@php.net for Windows build creation"
if [ ! -z "${CUT_RELEASE_BRANCH}" ]; then
  echo "3. Bump version in ${RELEASE_BRANCH}"
fi
if [ -z "$VERSION_EXTRA" ]; then
  echo "3. This appears to be a release build.  Reference README.RELEASE_PROCESS for further instruction."
fi
echo ""

echo "The announcement is: php-$RELEASE_VERSION.manifest"
